# Generated by Django 5.1.7 on 2025-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accepted_terms_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
