# Generated by Django 5.1.7 on 2025-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_accepted_terms_date_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('core', 'Core'), ('advanced', 'Advanced')], default='trial', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
