# Generated by Django 5.1.7 on 2025-03-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0005_user_accepted_terms_date_user_subscription_plan_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zip_code",
        ),
    ]
