# Generated by Django 5.1.7 on 2025-03-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_subscription_plan_remove_user_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accepted_terms_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_confirmation_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
