# Generated by Django 5.1.7 on 2025-10-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reward_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
