# Generated by Django 5.1.7 on 2026-03-12 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_user_reward_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivitylog",
            name="event_time",
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="event_type",
            field=models.CharField(
                choices=[("login", "Login"), ("logout", "Logout")],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
