# Generated by Django 5.1.7 on 2025-03-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="lesson_status",
            new_name="status",
        ),
    ]
