# Generated by Django 5.1.7 on 2025-03-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_rename_lesson_status_lesson_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lesson_images/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(default="pending", max_length=10),
        ),
    ]
