# Generated by Django 5.1.7 on 2025-03-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_alter_lesson_image_alter_lesson_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestions",
            name="options",
        ),
        migrations.AddField(
            model_name="quizquestions",
            name="options",
            field=models.ManyToManyField(to="lessons.quizquestionoptions"),
        ),
    ]
