# Generated by Django 5.1.7 on 2025-03-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_remove_quizquestions_options_quizquestions_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonsummary",
            name="lesson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.lesson",
            ),
        ),
    ]
