# Generated by Django 5.1.7 on 2025-03-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_lessonsummary_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
