# Generated by Django 5.1.7 on 2025-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_lesson_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
