# Generated by Django 5.1.7 on 2025-04-24 09:47

from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_quizresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonsummary",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
    ]
