# Generated by Django 5.1.7 on 2025-04-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0010_lessonsummary_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonsummary",
            name="remaining_time",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
