# Generated by Django 5.1.7 on 2026-03-12 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0011_lessonsummary_remaining_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sections",
            new_name="Section",
        ),
        migrations.RemoveField(
            model_name="quizquestions",
            name="options",
        ),
        migrations.RemoveField(
            model_name="quizquestions",
            name="quiz",
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="quizresult",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.quiz",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="quizresult",
            unique_together={("user", "quiz")},
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_length",
            field=models.CharField(
                choices=[("short", "Short"), ("medium", "Medium"), ("long", "Long")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lessonsummary",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.lesson",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=255)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lessons.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=10,
                    ),
                ),
                ("option_text", models.CharField(max_length=255)),
                ("correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="lessons.quizquestion",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="QuizQuestionOptions",
        ),
        migrations.DeleteModel(
            name="QuizQuestions",
        ),
        migrations.RemoveField(
            model_name="quizresult",
            name="lesson",
        ),
    ]
